language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: yume-wikijp@live.jp
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: QuySkraC+jE2ntQ9QbiPDFYGRdfy8zfu3n/tDQbbdhNytTwJ4h8w0f56Lk+2ULnLvfZ0vlHiUSrIXjChNspJhPZtzsygJmhYwY6V3FK8Z3PpC/WU1Vk8zxtiYTVboHgUiKmj4u9W/aSvhCAykr2XMEhbEMNTiaJEuxQO+TOkYFKafmfHUa3uJrIZ7aBLKTScav8SZT+Q7DShpR8bMon4yXpjtLuYO9V8b8O+CTO6IjUxnZG6zQmp+7M8oQq0GDqIJxwHHXml0YTfF3ITBdQ9F/Otjz7gs6My+6MhNaBJ/4PEi5PKEbe2PL/5ysMoH7y4AfSdCM2qs1BOqThngdsgSLHQZ/IVLM9wj2RZ6B7yvvapI9knyvAKoLfbKZVzzFvu5p05Q6eZFd1K/rCDWQ+nlguwpCbvXa8j/pNAn+u6cD10RdPYvDkbCN0PKNrcPUREzJSF1V3h1Y6mdZLE/GvlUwERqiJrEeclHktVk0/CHJKdTSvu5ZgS9InTgfxGSDQWmjhJgTYEbXf4J/tmdHsiUgPdSDJASdnaqXhMtNNBfyVckLNfIqTGE+13ObAj0tfzHNvrgu1TyZ7IFwkX210u9+Ms946SENCQc1fmzxspuzzz/IUifiC4Wq5olZl4X0rjpSCd1DZGPcILu+Wyo5peii17RWaJ+aaCO4Zu4JzrK+8=
